# vim: set ft=ansible
---

- name: Pre_Workload Actions
  include_tasks: pre_workload.yml

#- name: Demo app namespaces and pull secrets
#  include_tasks: image_pull_secret.yml

- name: Violation policies
  include_tasks: violation_policies.yml

- name: Demo application deployments
  include_tasks: deploy_demos.yml

- name: Network anomalies
  include_tasks: network_anomalies.yml

- name: Baseline processes
  include_tasks: baseline_processes.yml

# Not needed due to the latest ACS versions fix the 
# OpenShift policy false positive failures

# - name: Add OpenShift policy exceptions
#   include_tasks: openshift_policy_fix.yml
